adding tests for custom resources

diff --git a/pipelines/k8s.yaml b/pipelines/k8s.yaml
--- a/pipelines/k8s.yaml
+++ b/pipelines/k8s.yaml
@@ -9,11 +9,18 @@
     ls ${CHECK_PATH}
     cd $CHECK_PATH
     helm template --debug . > generated.yaml
-    echo helm been generated correctly
-    cat generated.yaml
-    /kubeconform -summary -output json --skip CustomResourceDefinition generated.yaml > "report.json" || true
+    helm kubeconform --verbose --summary .
+
+
+    # /kubeconform -summary -output json --skip CustomResourceDefinition generated.yaml > "report.json" || true
     echo "=============="
     cat report.json
+    if [[ jq -e '.summary.invalid > 0 or .summary.errors > 0' ]] report.json; then
+      echo "🚨 kubeconform reported invalid resources"
+      exit 1
+    else
+      echo "✅ kubeconform success"
+    fi
   artifacts:
     paths:
       - ${CHECK_PATH}/report.json
