fixing release again

diff --git a/pipelines/release.yaml b/pipelines/release.yaml
--- a/pipelines/release.yaml
+++ b/pipelines/release.yaml
@@ -131,25 +131,27 @@
     npx semantic-release --dry-run > release.log
     cat release.log
     
+    # 1. Determine CURRENT_VERSION
     CURRENT_VERSION=$(grep -i 'associated with version' release.log | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 || true)
     echo "CURRENT_VERSION=$CURRENT_VERSION" >> build.env
     
     # 2. Determine MAKE_RELEASE flag directly to the artifact
     if grep -qi 'the next release version is' release.log; then 
       echo "MAKE_RELEASE=TRUE" >> build.env
+      
     else 
       echo "MAKE_RELEASE=FALSE" >> build.env
     fi
     
-    # 3. Determine NEXT_VERSION
+    # 3. Determine NEXT_VERSION, if not set use CURRENT_VERSION
     NEXT_VERSION=$(grep -i 'the next release version is' release.log | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 || true)
+    if [ -z "$NEXT_VERSION" ]; then NEXT_VERSION=$CURRENT_VERSION; fi
     echo "NEXT_VERSION=$NEXT_VERSION" >> build.env
 
-    # validate that variables been set
-    if [ -z "$CURRENT_VERSION" ]; then echo "Error - CURRENT_VERSION is not set or empty"; exit 1; fi
-    if [ -z "$NEXT_VERSION" ]; then echo "Error - NEXT_VERSION is not set or empty"; exit 1; fi
-    if [ -z "$MAKE_RELEASE" ]; then echo "Error - MAKE_RELEASE is not set or empty"; exit 1; fi
-    
+    # this will point always to new version if release is available or a current version where there is no release 
+    BUILD_VERSION=$NEXT_VERSION"
+    echo "BUILD_VERSION=$BUILD_VERSION" >> build.env
+
     echo "=== Exported Variables ==="
     cat build.env
   artifacts:
@@ -168,6 +170,7 @@
     - if [ -z "$CURRENT_VERSION" ]; then echo "Error - CURRENT_VERSION is not set or empty"; exit 1; fi
     - if [ -z "$NEXT_VERSION" ]; then echo "Error - NEXT_VERSION is not set or empty"; exit 1; fi
     - if [ -z "$MAKE_RELEASE" ]; then echo "Error - MAKE_RELEASE is not set or empty"; exit 1; fi
+    - if [ -z "$BUILD_VERSION" ]; then echo "Error - BUILD_VERSION is not set or empty"; exit 1; fi
 
 #publish-release:
   #stage: release
