fix: use BUILS_VERSION for build versions, adding release job to pipeline

diff --git a/pipelines/release.yaml b/pipelines/release.yaml
--- a/pipelines/release.yaml
+++ b/pipelines/release.yaml
@@ -170,39 +170,36 @@
     - if [ -z "$MAKE_RELEASE" ]; then echo "Error - MAKE_RELEASE is not set or empty"; exit 1; fi
     - if [ -z "$BUILD_VERSION" ]; then echo "Error - BUILD_VERSION is not set or empty"; exit 1; fi
 
-#publish-release:
-  #stage: release
-  #image: node:20
-  #variables:
-    #GITLAB_TOKEN: "${CI_JOB_TOKEN}"
-    #GIT_DEPTH: "0"
-  #before_script:
-    #- git fetch --tags
-    #- npm install semantic-release @semantic-release/exec @semantic-release/git
-    #- npm install semantic-release @semantic-release/exec @semantic-release/git @semantic-release/gitlab
-  #script:
-    ## determining if need to create new version or not
-    #- |
-      #npx semantic-release --dry-run > release.log 2>&1 || true
-      #cat release.log
-      #if ! grep -qi 'the next release version is' release.log; then 
-        #echo "Semantic-release determined no new version is required. Exiting cleanly."
-        #exit 0
-      #fi
-    #- echo "=== Preparing Custom Changelog Script ==="
-    #- |
-      #cat << 'EOF' > update-changelog.sh
-      ##!/bin/bash
-      #VERSION=$1
-      #echo "## ${VERSION} - ${CI_COMMIT_MESSAGE}" >> CHANGELOG.md
-      #echo "$(date '+%Y-%m-%d')" >> CHANGELOG.md
-      #echo "- Commit URL: http://gitlab.dev.local/${CI_PROJECT_PATH}/-/tree/${CI_COMMIT_SHA}" >> CHANGELOG.md
-      #echo "- Pipeline: ${CI_PIPELINE_URL}" >> CHANGELOG.md
-      #echo "<br>" >> CHANGELOG.md
-      #echo "" >> CHANGELOG.md
-      #EOF
-    #- chmod +x update-changelog.sh
-    #- echo "=== Executing Semantic Release ==="
-    #- npx semantic-release
-  #rules:
-    #- if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
+.publish-release:
+  stage: release
+  image: node:20
+  variables:
+    GITLAB_TOKEN: "${CI_JOB_TOKEN}"
+  before_script:
+    - npm install semantic-release @semantic-release/exec @semantic-release/git @semantic-release/gitlab
+  script:
+    # determining if need to create new version or not
+    - |
+      npx semantic-release --dry-run > release.log 
+      cat release.log
+      if ! grep -qi 'the next release version is' release.log; then 
+        echo "Semantic-release determined no new version is required. Exiting cleanly."
+        exit 0
+      fi
+    - echo "=== Preparing Custom Changelog Script ==="
+    - |
+      cat << 'EOF' > update-changelog.sh
+      #!/bin/bash
+      VERSION=$1
+      echo "## ${VERSION} - ${CI_COMMIT_MESSAGE}" >> CHANGELOG.md
+      echo "$(date '+%Y-%m-%d')" >> CHANGELOG.md
+      echo "- Commit URL: http://gitlab.dev.local/${CI_PROJECT_PATH}/-/tree/${CI_COMMIT_SHA}" >> CHANGELOG.md
+      echo "- Pipeline: ${CI_PIPELINE_URL}" >> CHANGELOG.md
+      echo "<br>" >> CHANGELOG.md
+      echo "" >> CHANGELOG.md
+      EOF
+    - chmod +x update-changelog.sh
+    - echo "=== Executing Semantic Release ==="
+    - npx semantic-release
+  rules:
+    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
